from __future__ import annotations

from typing import Protocol


class JobSchedulerPort(Protocol):
    async def enqueue_acquisition(self, job_id: str) -> None: ...
    async def enqueue_verification(self, observation_id: str) -> None: ...
    async def enqueue_watch_evaluation(self, state_version_id: str) -> None: ...
    async def enqueue_outbox_dispatch(self) -> None: ...
