from __future__ import annotations

from typing import Protocol

from pipe4.domain.evidence.models import EvidenceRef, SourceProfile
from pipe4.domain.state.enums import StateType


class ProvenancePort(Protocol):
    async def get_evidence(self, evidence_ids: list[str]) -> list[EvidenceRef]: ...
    async def save_evidence(self, evidence: EvidenceRef) -> None: ...
    async def public_source_labels(self, *, source_ids: list[str], context_key: str) -> list[str]: ...


class SourceRegistryPort(Protocol):
    async def get_source(self, source_id: str) -> SourceProfile | None: ...
    async def get_source_for_context(self, source_id: str, *, entity_id: str, state_type: StateType) -> SourceProfile | None: ...
    async def list_sources(self) -> list[SourceProfile]: ...
    async def list_sources_for_context(self, *, entity_id: str, state_type: StateType) -> list[SourceProfile]: ...
    async def save_source(self, source: SourceProfile) -> None: ...
    async def record_outcome(self, source_id: str, *, entity_id: str, state_type: StateType, correct: bool) -> SourceProfile: ...
