<script lang="ts">
 import type { CurrentStatePresentation,StateValue } from '$lib/types/pipe4';
 type Props={state:CurrentStatePresentation;compact?:boolean}; let {state:presentation,compact=false}:Props=$props();
 let busy=$state(false);let actionMessage=$state<string|null>(null);let actionError=$state<string|null>(null);
 function valueText(value:StateValue|null|undefined):string{if(!value)return 'Not established';switch(value.kind){case'boolean':return value.value?'Yes':'No';case'quantity':return `${value.available}${value.total_capacity!=null?` of ${value.total_capacity}`:''} ${value.unit}`;case'duration':return value.label??`${Math.round(value.seconds/60)} min`;case'range':return `${value.minimum}–${value.maximum} ${value.unit}`;case'change':return value.summary??(value.changed?'Changed recently':'No material change');case'categorical':return value.value;}}
 function statusText(s:string){return ({CURRENT:'Current',VERIFYING:'Verification in progress',DISPUTED:'Conflicting reports',STALE:'Needs refresh',INFERRED:'Inferred — not independently verified',UNKNOWN:'Not established'} as Record<string,string>)[s]??s}
 async function requestAccess(){busy=true;actionError=null;try{const r=await fetch('/api/v1/pipe4/access-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entity_id:presentation.entity.entity_id,permission:'READ'})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error?.message??'Unable to request access');actionMessage=`Access request: ${j.data.status}`}catch(e){actionError=e instanceof Error?e.message:'Unable to request access'}finally{busy=false}}
 async function followChanges(){if(!presentation.identity||!presentation.value)return;busy=true;actionError=null;try{const r=await fetch('/api/v1/pipe4/watches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({condition:{identity:presentation.identity,operator:'NEQ',target:presentation.value,decision_context:{name:'consumer_discovery'},permission_scope_key:'current-user'}})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error?.message??'Unable to create watch');actionMessage='Following changes to this reality.'}catch(e){actionError=e instanceof Error?e.message:'Unable to follow changes'}finally{busy=false}}
</script>
<article class:compact class="state-card" data-status={presentation.status}>
 <header><div><p class="eyebrow">{presentation.entity.entity_type??'Current reality'}</p><h2>{presentation.entity.display_name??presentation.entity.entity_id}</h2></div><span class="status"><span aria-hidden="true" class="dot"></span>{statusText(presentation.status)}</span></header>
 <div class="answer"><span>{presentation.state_type?.toLowerCase().replace('_',' ')??'Current state'}</span><strong>{presentation.kind==='PROTECTED'?'Protected':valueText(presentation.value)}</strong></div>
 {#if presentation.message}<p class="message">{presentation.message}</p>{/if}
 {#if !compact && presentation.kind==='STATE'}<dl><div><dt>Observed</dt><dd>{presentation.observed_at?new Date(presentation.observed_at).toLocaleString():'—'}</dd></div><div><dt>Confidence</dt><dd>{presentation.confidence!=null?`${Math.round(presentation.confidence*100)}%`:'—'}</dd></div><div><dt>Evidence</dt><dd>{presentation.provenance?.evidence_count??0} record(s)</dd></div></dl>{/if}
 {#if presentation.kind==='PROTECTED'&&presentation.actions.includes('request_access')}<div class="button-row"><button class="secondary" disabled={busy} onclick={requestAccess}>Request access</button></div>{/if}
 {#if presentation.kind==='STATE'&&presentation.identity&&presentation.value&&presentation.actions.includes('watch')}<div class="button-row"><button class="secondary" disabled={busy} onclick={followChanges}>Follow changes</button></div>{/if}
 {#if actionMessage}<p class="notice">{actionMessage}</p>{/if}{#if actionError}<p class="error">{actionError}</p>{/if}
</article>
