import { z } from 'zod';
export const stateTypeSchema=z.enum(['AVAILABLE','ACCESSIBLE','WORKING','TIME','CHANGED']);
export const stateValueSchema=z.discriminatedUnion('kind',[
 z.object({kind:z.literal('boolean'),value:z.boolean()}),
 z.object({kind:z.literal('quantity'),available:z.number(),unit:z.string(),total_capacity:z.number().nullable().optional()}),
 z.object({kind:z.literal('duration'),seconds:z.number().nonnegative(),label:z.string().nullable().optional()}),
 z.object({kind:z.literal('range'),minimum:z.number(),maximum:z.number(),unit:z.string()}),
 z.object({kind:z.literal('change'),changed:z.boolean(),category:z.string().nullable().optional(),summary:z.string().nullable().optional(),previous_value_hash:z.string().nullable().optional()}),
 z.object({kind:z.literal('categorical'),value:z.string()})
]);
export const stateIdentitySchema=z.object({entity_id:z.string(),object_key:z.string(),state_type:stateTypeSchema,location_key:z.string().nullable().optional(),qualifiers:z.record(z.string(),z.union([z.string(),z.number(),z.boolean()])).optional()});
export const currentStateSchema=z.object({kind:z.enum(['STATE','PROTECTED','UNKNOWN']),status:z.enum(['CURRENT','VERIFYING','DISPUTED','STALE','INFERRED','UNKNOWN']),entity:z.object({entity_id:z.string(),display_name:z.string().nullable().optional(),entity_type:z.string().nullable().optional(),distance_m:z.number().nullable().optional()}),identity:stateIdentitySchema.nullable().optional(),state_type:stateTypeSchema.nullable().optional(),value:stateValueSchema.nullable().optional(),observed_at:z.string().nullable().optional(),expires_at:z.string().nullable().optional(),freshness_seconds:z.number().nullable().optional(),confidence:z.number().nullable().optional(),epistemic_status:z.string().nullable().optional(),verification_status:z.string().nullable().optional(),state_version_id:z.string().nullable().optional(),access_request_status:z.string().nullable().optional(),actions:z.array(z.string()),message:z.string().nullable().optional(),provenance:z.object({source_count:z.number(),evidence_count:z.number(),independent_origin_count:z.number(),public_source_labels:z.array(z.string())}).nullable().optional()});
export const nearbySchema=z.array(z.object({score:z.number(),distance_m:z.number(),current:currentStateSchema}));
export const watchConditionSchema=z.object({identity:stateIdentitySchema,operator:z.enum(['EQ','NEQ','GT','GTE','LT','LTE']),target:stateValueSchema,decision_context:z.object({name:z.string().optional(),urgency:z.number().optional(),uncertainty_consequence:z.number().optional(),requested_quantity:z.number().nullable().optional(),unit:z.string().nullable().optional()}).optional(),permission_scope_key:z.string().optional()});
export const watchViewSchema=z.object({watch_id:z.string(),watch_process_id:z.string(),subscriber_subject:z.string(),status:z.enum(['ACTIVE','ALERTING','PAUSED']),condition:watchConditionSchema,created_at:z.string(),updated_at:z.string(),last_triggered_at:z.string().nullable().optional()});
export const accessRequestSchema=z.object({access_request_id:z.string(),requester_subject:z.string(),target_entity_id:z.string(),target_identity_key:z.string().nullable().optional(),requested_permission:z.string(),requested_scope:z.record(z.string(),z.union([z.string(),z.number(),z.boolean()])),status:z.enum(['PENDING','APPROVED','DENIED','REVOKED','EXPIRED','CANCELLED']),requested_at:z.string(),decided_at:z.string().nullable().optional(),decision_reason:z.string().nullable().optional(),expires_at:z.string().nullable().optional()});
export const targetedAcquisitionSchema=z.object({targeted_request_id:z.string(),state_request_id:z.string(),target_subject:z.string(),status:z.enum(['OFFERED','ACCEPTED','DECLINED','EXPIRED','COMPLETED']),offered_at:z.string(),expires_at:z.string(),accepted_at:z.string().nullable().optional(),completed_observation_id:z.string().nullable().optional(),reward_label:z.string().nullable().optional(),identity:stateIdentitySchema.nullable().optional(),what_to_confirm:z.string().nullable().optional()});
export const entityCandidateSchema=z.object({entity_id:z.string(),display_name:z.string(),entity_type:z.string(),distance_m:z.number().nullable().optional(),confidence:z.number()});
export const witnessInterpretationSchema=z.object({state_type:stateTypeSchema.nullable().optional(),value:stateValueSchema.nullable().optional(),interpretation_confidence:z.number(),entity_candidates:z.array(entityCandidateSchema),selected_entity_id:z.string().nullable().optional(),requires_clarification:z.boolean(),clarification_question:z.string().nullable().optional(),used_ai:z.boolean()});
