from __future__ import annotations

from typing import Protocol

from pipe4.domain.access.models import AccessRequest, PermissionGrant
from pipe4.domain.acquisition.models import (
    AcquisitionAttempt,
    AcquisitionJob,
    StateRequest,
    TargetedAcquisitionRequest,
)
from pipe4.domain.contradiction import ContradictionRecord
from pipe4.domain.entities.models import ReferenceEntity
from pipe4.domain.events.models import DomainEvent, OutboxRecord
from pipe4.domain.observation.models import ObservationRecord
from pipe4.domain.state.identity import StateIdentity
from pipe4.domain.state.models import StateVersion
from pipe4.domain.watch.models import WatchProcess, WatchSubscription


class StateRepository(Protocol):
    async def current(self, identity_key: str) -> StateVersion | None: ...
    async def get_version(self, state_version_id: str) -> StateVersion | None: ...
    async def history(self, identity_key: str, *, limit: int = 50) -> list[StateVersion]: ...
    async def list_current(self) -> list[StateVersion]: ...


class StatePublicationPort(Protocol):
    async def publish_state(
        self,
        state: StateVersion,
        *,
        events: list[DomainEvent],
        idempotency_scope: str | None = None,
        idempotency_key: str | None = None,
    ) -> StateVersion: ...
    async def expire_state(self, state_version_id: str, *, event: DomainEvent) -> StateVersion: ...


class ObservationRepository(Protocol):
    async def save_observation(self, observation: ObservationRecord) -> ObservationRecord: ...
    async def get_observation(self, observation_id: str) -> ObservationRecord | None: ...
    async def update_observation(self, observation: ObservationRecord) -> ObservationRecord: ...


class RequestRepository(Protocol):
    async def find_active_request(self, fingerprint: str) -> StateRequest | None: ...
    async def save_request(self, request: StateRequest) -> StateRequest: ...
    async def get_request(self, request_id: str) -> StateRequest | None: ...
    async def active_demand_count(self, identity_key: str) -> int: ...


class AcquisitionRepository(Protocol):
    async def save_job(self, job: AcquisitionJob) -> AcquisitionJob: ...
    async def get_job(self, job_id: str) -> AcquisitionJob | None: ...
    async def pending_jobs(self, *, limit: int = 100) -> list[AcquisitionJob]: ...
    async def save_attempt(self, attempt: AcquisitionAttempt) -> AcquisitionAttempt: ...
    async def attempts_for_job(self, job_id: str) -> list[AcquisitionAttempt]: ...


class WatchRepository(Protocol):
    async def get_process_by_fingerprint(self, fingerprint: str) -> WatchProcess | None: ...
    async def get_process(self, watch_process_id: str) -> WatchProcess | None: ...
    async def save_process(self, process: WatchProcess) -> WatchProcess: ...
    async def save_subscription(self, subscription: WatchSubscription) -> WatchSubscription: ...
    async def get_subscription(self, watch_id: str) -> WatchSubscription | None: ...
    async def list_subscriptions(self, subject: str) -> list[WatchSubscription]: ...
    async def subscriptions_for_identity(self, identity_key: str) -> list[WatchSubscription]: ...
    async def delete_subscription(self, watch_id: str) -> None: ...
    async def active_watch_count(self, identity_key: str) -> int: ...


class AccessRepository(Protocol):
    async def save_access_request(self, request: AccessRequest) -> AccessRequest: ...
    async def get_access_request(self, request_id: str) -> AccessRequest | None: ...
    async def list_access_requests(self, subject: str) -> list[AccessRequest]: ...
    async def save_grant(self, grant: PermissionGrant) -> PermissionGrant: ...
    async def has_grant(
        self, *, subject: str, entity_id: str, identity_key: str | None, permission: str
    ) -> bool: ...
    async def revoke_grant(self, access_request_id: str, *, revoked_at) -> None: ...
    async def pending_request_status(
        self, *, subject: str, entity_id: str, identity_key: str | None
    ) -> str | None: ...


class EntityRepository(Protocol):
    async def save_entity(self, entity: ReferenceEntity) -> ReferenceEntity: ...
    async def get_entity(self, entity_id: str) -> ReferenceEntity | None: ...
    async def list_entities(self) -> list[ReferenceEntity]: ...


class TargetedAcquisitionRepository(Protocol):
    async def save_targeted(self, request: TargetedAcquisitionRequest) -> TargetedAcquisitionRequest: ...
    async def get_targeted(self, request_id: str) -> TargetedAcquisitionRequest | None: ...
    async def list_targeted_for_subject(self, subject: str) -> list[TargetedAcquisitionRequest]: ...


class ContradictionRepository(Protocol):
    async def save_contradiction(self, contradiction: ContradictionRecord) -> ContradictionRecord: ...
    async def open_for_identity(self, identity_key: str) -> list[ContradictionRecord]: ...


class EventRepository(Protocol):
    async def append_event(self, event: DomainEvent) -> None: ...
    async def append_events(self, events: list[DomainEvent]) -> None: ...
    async def list_events(self, *, limit: int = 200) -> list[DomainEvent]: ...
    async def pending_outbox(self, *, limit: int = 100) -> list[OutboxRecord]: ...
    async def mark_outbox_published(self, outbox_id: str, *, published_at) -> None: ...
    async def mark_outbox_failed(self, outbox_id: str, *, error: str) -> None: ...
