"""Pipe 4 production schema.

Revision ID: 0001_pipe4_production
Revises:
"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
revision='0001_pipe4_production';down_revision=None;branch_labels=None;depends_on=None

def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    op.create_table('state_version',sa.Column('state_version_id',sa.String(36),primary_key=True),sa.Column('identity_key',sa.String(64),nullable=False),sa.Column('entity_id',sa.String(160),nullable=False),sa.Column('object_key',sa.String(200),nullable=False),sa.Column('state_type',sa.String(32),nullable=False),sa.Column('location_key',sa.String(200)),sa.Column('qualifiers',sa.JSON(),nullable=False),sa.Column('value',sa.JSON(),nullable=False),sa.Column('epistemic_status',sa.String(40),nullable=False),sa.Column('verification_status',sa.String(40),nullable=False),sa.Column('lifecycle_status',sa.String(40),nullable=False),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('received_at',sa.DateTime(timezone=True),nullable=False),sa.Column('valid_from',sa.DateTime(timezone=True),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True)),sa.Column('last_verified_at',sa.DateTime(timezone=True)),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('confidence_breakdown',sa.JSON()),sa.Column('policy_version',sa.String(64),nullable=False),sa.Column('visibility',sa.String(32),nullable=False),sa.Column('permission_tags',sa.JSON(),nullable=False),sa.Column('source_ids',sa.JSON(),nullable=False),sa.Column('evidence_ids',sa.JSON(),nullable=False),sa.Column('predecessor_state_version_id',sa.String(36),sa.ForeignKey('state_version.state_version_id')),sa.Column('version',sa.Integer(),nullable=False),sa.Column('correlation_id',sa.String(100)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('identity_key','version',name='uq_state_version_identity_version'))
    op.create_index('ix_state_version_identity_key','state_version',['identity_key']);op.create_index('ix_state_version_entity_id','state_version',['entity_id']);op.create_index('ix_state_version_state_type','state_version',['state_type']);op.create_index('ix_state_version_observed_at','state_version',['observed_at']);op.create_index('ix_state_version_expires_at','state_version',['expires_at'])
    op.create_table('current_state_projection',sa.Column('identity_key',sa.String(64),primary_key=True),sa.Column('state_version_id',sa.String(36),sa.ForeignKey('state_version.state_version_id'),nullable=False,unique=True),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('observation',sa.Column('observation_id',sa.String(36),primary_key=True),sa.Column('identity',sa.JSON(),nullable=False),sa.Column('proposed_value',sa.JSON(),nullable=False),sa.Column('source_id',sa.String(160),nullable=False),sa.Column('actor_subject',sa.String(200)),sa.Column('epistemic_status',sa.String(40),nullable=False),sa.Column('status',sa.String(40),nullable=False),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('received_at',sa.DateTime(timezone=True),nullable=False),sa.Column('latitude',sa.Float()),sa.Column('longitude',sa.Float()),sa.Column('location_accuracy_m',sa.Float()),sa.Column('location_description',sa.Text()),sa.Column('location_evidence_type',sa.String(40),nullable=False),sa.Column('evidence_ids',sa.JSON(),nullable=False),sa.Column('original_input_ref',sa.String(500)),sa.Column('interpretation_confidence',sa.Float()),sa.Column('consumed_state_version_id',sa.String(36)),sa.Column('correlation_id',sa.String(100)))
    op.create_table('state_request',sa.Column('request_id',sa.String(36),primary_key=True),sa.Column('identity',sa.JSON(),nullable=False),sa.Column('identity_key',sa.String(64),nullable=False),sa.Column('requester_subject',sa.String(200),nullable=False),sa.Column('decision_context',sa.JSON(),nullable=False),sa.Column('gap_reason',sa.String(50),nullable=False),sa.Column('fingerprint',sa.String(64),nullable=False),sa.Column('status',sa.String(40),nullable=False),sa.Column('demand_count',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('resolved_state_version_id',sa.String(36)))
    op.create_index('ix_state_request_fingerprint','state_request',['fingerprint']);op.create_index('ix_state_request_identity_key','state_request',['identity_key'])
    op.create_table('acquisition_job',sa.Column('job_id',sa.String(36),primary_key=True),sa.Column('request_id',sa.String(36),sa.ForeignKey('state_request.request_id'),nullable=False),sa.Column('identity',sa.JSON(),nullable=False),sa.Column('decision_context',sa.JSON(),nullable=False),sa.Column('status',sa.String(40),nullable=False),sa.Column('candidate_source_ids',sa.JSON(),nullable=False),sa.Column('idempotency_key',sa.String(128),nullable=False,unique=True),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('deadline_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('acquisition_attempt',sa.Column('attempt_id',sa.String(36),primary_key=True),sa.Column('job_id',sa.String(36),sa.ForeignKey('acquisition_job.job_id'),nullable=False),sa.Column('source_id',sa.String(160),nullable=False),sa.Column('status',sa.String(40),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True),nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('latency_ms',sa.Integer()),sa.Column('cost_units',sa.Float(),nullable=False),sa.Column('result_observation_id',sa.String(36)),sa.Column('reason',sa.Text()))
    op.create_table('watch_process',sa.Column('watch_process_id',sa.String(36),primary_key=True),sa.Column('fingerprint',sa.String(64),nullable=False,unique=True),sa.Column('condition',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('watch_subscription',sa.Column('watch_id',sa.String(36),primary_key=True),sa.Column('watch_process_id',sa.String(36),sa.ForeignKey('watch_process.watch_process_id'),nullable=False),sa.Column('subscriber_subject',sa.String(200),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('last_triggered_at',sa.DateTime(timezone=True)))
    op.create_table('access_request',sa.Column('access_request_id',sa.String(36),primary_key=True),sa.Column('requester_subject',sa.String(200),nullable=False),sa.Column('target_entity_id',sa.String(160),nullable=False),sa.Column('target_identity_key',sa.String(64)),sa.Column('requested_permission',sa.String(50),nullable=False),sa.Column('requested_scope',sa.JSON(),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('requested_at',sa.DateTime(timezone=True),nullable=False),sa.Column('decided_at',sa.DateTime(timezone=True)),sa.Column('decided_by_subject',sa.String(200)),sa.Column('decision_reason',sa.Text()),sa.Column('granted_scope',sa.JSON()),sa.Column('expires_at',sa.DateTime(timezone=True)))
    op.create_table('permission_grant',sa.Column('grant_id',sa.String(36),primary_key=True),sa.Column('access_request_id',sa.String(36),sa.ForeignKey('access_request.access_request_id'),nullable=False),sa.Column('subject',sa.String(200),nullable=False),sa.Column('target_entity_id',sa.String(160),nullable=False),sa.Column('target_identity_key',sa.String(64)),sa.Column('permission',sa.String(50),nullable=False),sa.Column('scope',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True)),sa.Column('revoked_at',sa.DateTime(timezone=True)))
    op.create_table('targeted_acquisition_request',sa.Column('targeted_request_id',sa.String(36),primary_key=True),sa.Column('state_request_id',sa.String(36),nullable=False),sa.Column('target_subject',sa.String(200),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('offered_at',sa.DateTime(timezone=True),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('accepted_at',sa.DateTime(timezone=True)),sa.Column('completed_observation_id',sa.String(36)),sa.Column('reward_label',sa.String(120)))
    op.create_table('contradiction',sa.Column('contradiction_id',sa.String(36),primary_key=True),sa.Column('identity_key',sa.String(64),nullable=False),sa.Column('incumbent_state_version_id',sa.String(36),nullable=False),sa.Column('competing_observation_id',sa.String(36)),sa.Column('competing_state_version_id',sa.String(36)),sa.Column('material',sa.Boolean(),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('reason',sa.Text(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('resolved_at',sa.DateTime(timezone=True)))
    op.create_table('reference_entity',sa.Column('entity_id',sa.String(160),primary_key=True),sa.Column('entity_type',sa.String(120),nullable=False),sa.Column('display_name',sa.String(240),nullable=False),sa.Column('latitude',sa.Float()),sa.Column('longitude',sa.Float()),sa.Column('geom',Geometry('POINT',srid=4326)),sa.Column('aliases',sa.JSON(),nullable=False),sa.Column('provisional',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('source_profile',sa.Column('source_id',sa.String(160),primary_key=True),sa.Column('source_type',sa.String(80),nullable=False),sa.Column('authority_scopes',sa.JSON(),nullable=False),sa.Column('reliability',sa.Float(),nullable=False),sa.Column('evidence_capability',sa.Float(),nullable=False),sa.Column('expected_latency_ms',sa.Integer(),nullable=False),sa.Column('cost_units',sa.Float(),nullable=False),sa.Column('provider_key',sa.String(160)),sa.Column('correct_outcomes',sa.Integer(),nullable=False),sa.Column('incorrect_outcomes',sa.Integer(),nullable=False))
    op.create_table('source_reliability_outcome',sa.Column('outcome_id',sa.String(36),primary_key=True),sa.Column('source_id',sa.String(160),sa.ForeignKey('source_profile.source_id'),nullable=False),sa.Column('entity_id',sa.String(160),nullable=False),sa.Column('state_type',sa.String(32),nullable=False),sa.Column('correct',sa.Boolean(),nullable=False),sa.Column('previous_reliability',sa.Float(),nullable=False),sa.Column('new_reliability',sa.Float(),nullable=False),sa.Column('recorded_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('evidence_metadata',sa.Column('evidence_id',sa.String(36),primary_key=True),sa.Column('evidence_class',sa.String(60),nullable=False),sa.Column('source_id',sa.String(160),nullable=False),sa.Column('origin_key',sa.String(200),nullable=False),sa.Column('content_hash',sa.String(64),nullable=False),sa.Column('captured_at',sa.DateTime(timezone=True),nullable=False),sa.Column('received_at',sa.DateTime(timezone=True),nullable=False),sa.Column('object_ref',sa.String(500)),sa.Column('evidence_metadata',sa.JSON(),nullable=False))
    op.create_table('state_evidence_link',sa.Column('state_version_id',sa.String(36),sa.ForeignKey('state_version.state_version_id'),primary_key=True),sa.Column('evidence_id',sa.String(36),sa.ForeignKey('evidence_metadata.evidence_id'),primary_key=True))
    op.create_table('domain_event',sa.Column('event_id',sa.String(36),primary_key=True),sa.Column('event_type',sa.String(120),nullable=False),sa.Column('aggregate_type',sa.String(80),nullable=False),sa.Column('aggregate_id',sa.String(160),nullable=False),sa.Column('occurred_at',sa.DateTime(timezone=True),nullable=False),sa.Column('correlation_id',sa.String(100)),sa.Column('payload',sa.JSON(),nullable=False))
    op.create_table('outbox',sa.Column('outbox_id',sa.String(36),primary_key=True),sa.Column('event_id',sa.String(36),sa.ForeignKey('domain_event.event_id'),nullable=False,unique=True),sa.Column('event_payload',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('published_at',sa.DateTime(timezone=True)),sa.Column('attempts',sa.Integer(),nullable=False),sa.Column('last_error',sa.Text()))
    op.create_table('idempotency_record',sa.Column('scope',sa.String(120),primary_key=True),sa.Column('idempotency_key',sa.String(200),primary_key=True),sa.Column('result_id',sa.String(160),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))

def downgrade():
    for table in ['idempotency_record','outbox','domain_event','state_evidence_link','evidence_metadata','source_reliability_outcome','source_profile','reference_entity','contradiction','targeted_acquisition_request','permission_grant','access_request','watch_subscription','watch_process','acquisition_attempt','acquisition_job','state_request','observation','current_state_projection','state_version']:
        op.drop_table(table)
